### ISSUE TITLE
Position doesn't save properly

### ISSUE THREAD

**Issue by rujind** [ConteAlmaviva/ticker#2]
I have to unload and reload this addon for it to be put in the proper position.

**Comment by ConteAlmaviva** [comment]
The position and other addon properties have a default set of values defined in ticker.lua. When the addon is loaded, it reads from a settings.json file on disk (if it exists) and overwrites the default values with what is in that settings.json file. (This is how most if not all Ashita v3 addons work.)

When the addon is unloaded (e.g. by typing `/addon unload ticker` in game or shutting down the client), the current X and Y positions of the ticker text object are read in and saved to that settings.json file along with the other text object properties like font family, size, background visibility, color, etc. What that means is the addon isn't going to respond to changes you make to settings.json in real time (while the addon is loaded), and will overwrite any changes you make to the file whenever you next unload or reload it. The only real property that you can change in real time on this and most Ashita text addons is the position on screen via shift+click and drag (it'd be more trouble than it's worth to add an interface to change font face, size, etc. in-game; just editing the settings.json file is honestly more straightforward). If you move the object this way, its new position will be saved when the addon unloads, but there's a caveat - there's only a single settings.json file used by the addon, so if you dual box and have the addon loaded on multiple characters, the last one to unload it is going to be what gets saved in the settings file. If you move the text object on one character, but not the other, and then shut down on the character you moved it on, it'll save the settings, but they'll be overridden if you then shut down on the character you did not move the text object on.
